# Site settings
title: Thendralum Mellisaiyum
email: rkmanikarthick@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some random blogs
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://manikandan-k.github.io" # the base hostname & protocol for your site
url: "http://localhost:4000/"
twitter_username: Kmanikandan26
github_username:  Manikandan-K

# Build settings
markdown: kramdown
